spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  application:
    name: music_app

  datasource:
    url: jdbc:postgresql://localhost:5678/music_app_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: "group6"
    password: "group6"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
            trust: "*"
          starttls:
            enable: false
    protocol: smtp
  redis:
    host: localhost
    port: 6379
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
    google:
      client-id: 1078270987220-iq6dluklb03qlrsc4rgmfp6hireno8cn.apps.googleusercontent.com
  file:
    uploads:
      photos-output-path: ./uploads

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json # Không ảnh hưởng đến multipart
  swagger-ui:
    supportedSubmitMethods: [get, post, put, delete]
    path: /swagger-ui.html

server:
  servlet:
    context-path: /api/v1/
  port: 8088

logging:
  level:
    org.springframework.web: DEBUG